"""Render findings.md and the coverage heatmap. The sample-size caveat is non-negotiable
and printed alongside every verdict."""
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from .config import FWD_WINDOWS, HEATMAP_PNG, STUDY_DIR

CAVEAT = ("> **Sample size caveat.** This is a smoke test over ~40-50 basket-months. "
          "No result here is statistically significant — at best it is suggestive. "
          "Effect size and n are reported together; a positive IC means 'worth a real "
          "study', not 'alpha found'. The six combinations (2 attribution modes x Study A "
          "+ 2 Study B aggregations) are NOT independent confirmations: they share one "
          "sparse corpus and overlapping baskets, so a result that repeats across them is "
          "one observation viewed six ways. An IC near zero — even if consistently signed "
          "— means 'no detectable signal', not a directional (e.g. contrarian) one.")


def _ic_row(label: str, ic: dict) -> str:
    cells = " | ".join(
        f"{ic[w]['ic_mean']:+.3f} (n={ic[w]['n']})" for w in FWD_WINDOWS)
    return f"| {label} | {cells} |"


def render_markdown(results: dict) -> str:
    lines = ["# a16z Research-Coverage Signal — Findings", "",
             "_Generated by `python -m study.run`._", "", CAVEAT, ""]
    win_hdr = " | ".join(f"fwd {w}m IC" for w in FWD_WINDOWS)
    for mode, r in results.items():
        lines += [f"## Attribution mode: `{mode}`", ""]
        a = r["study_a"]
        lines += [f"### Study A — basket level — **verdict: {a['verdict']}**", "",
                  f"| signal | {win_hdr} |", "|" + "---|" * (len(FWD_WINDOWS) + 1),
                  _ic_row("coverage_momentum", a["ic"]), ""]
        bt = " | ".join(f"{a['backtest'][w]['mean_spread']:+.4f}" for w in FWD_WINDOWS)
        lines += [f"Toy long/short mean spread: {bt}", ""]
        for agg, b in r["study_b"].items():
            lines += [f"### Study B — token level (`{agg}`) — **verdict: {b['verdict']}**", "",
                      f"| signal | {win_hdr} |", "|" + "---|" * (len(FWD_WINDOWS) + 1),
                      _ic_row(f"conviction ({agg})", b["ic"]), ""]
            qs = " | ".join(f"{b['quartile_spread'][w]:+.4f}" for w in FWD_WINDOWS)
            lines += [f"Quartile long/short spread: {qs}", ""]
    lines += ["## Coverage heatmap", "", f"![coverage]({HEATMAP_PNG.name})", ""]
    return "\n".join(lines)


def render_heatmap(coverage: pd.DataFrame) -> None:
    """coverage: long-form [month, basket, coverage_share]. Saves HEATMAP_PNG."""
    if coverage.empty:
        return  # nothing to plot (never happens on real data; guards test/edge callers)
    wide = coverage.pivot(index="basket", columns="month", values="coverage_share").fillna(0.0)
    STUDY_DIR.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(max(8, wide.shape[1] * 0.18), 3 + wide.shape[0] * 0.4))
    im = ax.imshow(wide.values, aspect="auto", cmap="magma")
    ax.set_yticks(range(wide.shape[0]))
    ax.set_yticklabels(wide.index)
    step = max(1, wide.shape[1] // 24)
    ax.set_xticks(range(0, wide.shape[1], step))
    ax.set_xticklabels([str(m) for m in wide.columns[::step]], rotation=90, fontsize=7)
    ax.set_title("a16z research coverage share by basket over time")
    fig.colorbar(im, ax=ax, label="coverage share")
    fig.tight_layout()
    fig.savefig(HEATMAP_PNG, dpi=120)
    plt.close(fig)
